# Server and project configuration
sonar.host.url=https://sonar.wpengine.io/
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

# Project identifiers
sonar.projectName=pipelines-site-template
sonar.projectKey=wpengine_pipelines-site-template_9b40e31d-8243-4476-a95b-4b8ba08717cf

# Paths to source code directories (relative paths)
sonar.sources=.

# Exclusions
sonar.exclusions=vendor/**,plugins/**,themes/**,mu-plugins/**,node_modules/**

# Paths to test code directories (relative paths)
sonar.tests=.
sonar.test.inclusions=**/*Test.php
